# Generated by Django 4.2 on 2025-11-05 02:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rut",
                    models.CharField(
                        help_text="Chilean RUT in format XX.XXX.XXX-X",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="RUT must be in format: XX.XXX.XXX-X",
                                regex="^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$",
                            )
                        ],
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("retail", "Retail / Comercio"),
                            ("food", "Food & Beverage / Alimentos y Bebidas"),
                            ("manufacturing", "Manufacturing / Manufactura"),
                            ("services", "Services / Servicios"),
                            ("technology", "Technology / Tecnología"),
                            ("construction", "Construction / Construcción"),
                            ("agriculture", "Agriculture / Agricultura"),
                            ("healthcare", "Healthcare / Salud"),
                            ("education", "Education / Educación"),
                            ("other", "Other / Otro"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("micro", "Micro (1-9 employees)"),
                            ("small", "Small (10-49 employees)"),
                            ("medium", "Medium (50-249 employees)"),
                        ],
                        default="micro",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "db_table": "companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner / Dueño"),
                            ("admin", "Administrator / Administrador"),
                            ("manager", "Manager / Gerente"),
                            ("analyst", "Analyst / Analista"),
                            ("viewer", "Viewer / Visualizador"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="Fine-grained permissions: {can_upload: true, can_export: false, ...}",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_users",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                related_name="companies",
                through="companies.UserCompany",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usercompany",
            index=models.Index(
                fields=["user", "company"], name="user_compan_user_id_0b698d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercompany",
            index=models.Index(fields=["role"], name="user_compan_role_0e8e84_idx"),
        ),
        migrations.AddIndex(
            model_name="usercompany",
            index=models.Index(
                fields=["is_active"], name="user_compan_is_acti_a6f00e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercompany",
            unique_together={("user", "company")},
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["rut"], name="companies_rut_5527a3_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["industry"], name="companies_industr_7891ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["created_at"], name="companies_created_c84a3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_active"], name="companies_is_acti_e9a12b_idx"
            ),
        ),
    ]
