# Generated by Django 4.2 on 2025-11-05 02:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(db_index=True, max_length=50)),
                ("metric_name", models.CharField(db_index=True, max_length=100)),
                ("value", models.FloatField()),
                ("period", models.CharField(max_length=50)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        help_text="Number of companies in benchmark (minimum 10 for privacy)"
                    ),
                ),
                ("percentile_25", models.FloatField(blank=True, null=True)),
                ("percentile_50", models.FloatField(blank=True, null=True)),
                ("percentile_75", models.FloatField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "benchmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YearlyAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Yearly metrics for annual reports and long-term trends"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "yearly_aggregations",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(db_index=True)),
                ("year", models.IntegerField(db_index=True)),
                ("week_number", models.IntegerField()),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Weekly metrics aggregated from daily data"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "weekly_aggregations",
                "ordering": ["-year", "-week_number"],
            },
        ),
        migrations.CreateModel(
            name="QuarterlyAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quarter", models.IntegerField(db_index=True)),
                ("year", models.IntegerField(db_index=True)),
                (
                    "metrics",
                    models.JSONField(help_text="Quarterly metrics for trend analysis"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarterly_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "quarterly_aggregations",
                "ordering": ["-year", "-quarter"],
            },
        ),
        migrations.CreateModel(
            name="ProductAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(db_index=True, max_length=255)),
                ("period", models.CharField(max_length=50)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Product metrics: sales, revenue, margin, velocity, etc."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "product_aggregations",
                "ordering": ["-period"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField(db_index=True)),
                ("year", models.IntegerField(db_index=True)),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Monthly metrics: primary analytics view for PYMEs"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "monthly_aggregations",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="DailyAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Daily metrics: revenue, transactions, avg_ticket, etc."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "daily_aggregations",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=255)),
                ("period", models.CharField(max_length=50)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Customer metrics: LTV, frequency, recency, avg_order, etc."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "customer_aggregations",
                "ordering": ["-period"],
            },
        ),
        migrations.CreateModel(
            name="CategoryAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=255)),
                ("period", models.CharField(max_length=50)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Category metrics: revenue, product_count, top_products, etc."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_aggregations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "category_aggregations",
                "ordering": ["-period"],
            },
        ),
        migrations.AddIndex(
            model_name="benchmark",
            index=models.Index(
                fields=["industry", "metric_name"], name="benchmarks_industr_8d6487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benchmark",
            index=models.Index(
                fields=["period_type", "created_at"],
                name="benchmarks_period__c0c866_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="benchmark",
            unique_together={("industry", "metric_name", "period", "period_type")},
        ),
        migrations.AddIndex(
            model_name="yearlyaggregation",
            index=models.Index(
                fields=["company", "year"], name="yearly_aggr_company_411b1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yearlyaggregation",
            index=models.Index(fields=["year"], name="yearly_aggr_year_2d72dd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="yearlyaggregation",
            unique_together={("company", "year")},
        ),
        migrations.AddIndex(
            model_name="weeklyaggregation",
            index=models.Index(
                fields=["company", "year", "week_number"],
                name="weekly_aggr_company_a440a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyaggregation",
            index=models.Index(
                fields=["week_start"], name="weekly_aggr_week_st_40f546_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weeklyaggregation",
            unique_together={("company", "year", "week_number")},
        ),
        migrations.AddIndex(
            model_name="quarterlyaggregation",
            index=models.Index(
                fields=["company", "year", "quarter"],
                name="quarterly_a_company_62154f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quarterlyaggregation",
            index=models.Index(
                fields=["year", "quarter"], name="quarterly_a_year_b28b42_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quarterlyaggregation",
            unique_together={("company", "year", "quarter")},
        ),
        migrations.AddIndex(
            model_name="productaggregation",
            index=models.Index(
                fields=["company", "product_id", "period_type"],
                name="product_agg_company_9e6298_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productaggregation",
            index=models.Index(
                fields=["company", "period_type"], name="product_agg_company_df44e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productaggregation",
            unique_together={("company", "product_id", "period", "period_type")},
        ),
        migrations.AddIndex(
            model_name="monthlyaggregation",
            index=models.Index(
                fields=["company", "year", "month"],
                name="monthly_agg_company_c9d614_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyaggregation",
            index=models.Index(
                fields=["year", "month"], name="monthly_agg_year_555e04_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyaggregation",
            unique_together={("company", "year", "month")},
        ),
        migrations.AddIndex(
            model_name="dailyaggregation",
            index=models.Index(
                fields=["company", "date"], name="daily_aggre_company_c88c2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyaggregation",
            index=models.Index(fields=["date"], name="daily_aggre_date_a7a8b9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailyaggregation",
            unique_together={("company", "date")},
        ),
        migrations.AddIndex(
            model_name="customeraggregation",
            index=models.Index(
                fields=["company", "customer_id", "period_type"],
                name="customer_ag_company_67a24d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeraggregation",
            index=models.Index(
                fields=["company", "period_type"], name="customer_ag_company_7632aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customeraggregation",
            unique_together={("company", "customer_id", "period", "period_type")},
        ),
        migrations.AddIndex(
            model_name="categoryaggregation",
            index=models.Index(
                fields=["company", "category", "period_type"],
                name="category_ag_company_55dd7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="categoryaggregation",
            index=models.Index(
                fields=["company", "period_type"], name="category_ag_company_fcacff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoryaggregation",
            unique_together={("company", "category", "period", "period_type")},
        ),
    ]
