# Generated by Django 4.2 on 2025-11-05 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "column_mappings",
                    models.JSONField(
                        default=dict,
                        help_text="Maps user CSV columns to COLUMN_SCHEMA fields",
                    ),
                ),
                ("original_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("updated_rows", models.IntegerField(default=0)),
                ("error_rows", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed error information by row",
                        null=True,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Transaction data following COLUMN_SCHEMA from src/core/constants.py"
                    ),
                ),
                ("transaction_date", models.DateTimeField(db_index=True)),
                ("transaction_id", models.CharField(db_index=True, max_length=255)),
                ("product_id", models.CharField(db_index=True, max_length=255)),
                (
                    "customer_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("quantity", models.FloatField()),
                ("price_total", models.FloatField()),
                ("cost_total", models.FloatField(blank=True, null=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_transactions",
                        to="companies.company",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="processing.upload",
                    ),
                ),
            ],
            options={
                "db_table": "raw_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="DataUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=50)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rows_before", models.IntegerField(default=0)),
                ("rows_after", models.IntegerField(default=0)),
                ("rows_updated", models.IntegerField(default=0)),
                ("rows_added", models.IntegerField(default=0)),
                ("rows_deleted", models.IntegerField(default=0)),
                (
                    "changes_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed summary of changes by aggregation level",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_updates",
                        to="companies.company",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_updates",
                        to="processing.upload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_updates",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapping_name", models.CharField(max_length=100)),
                (
                    "mappings",
                    models.JSONField(
                        help_text="Maps CSV column names to COLUMN_SCHEMA fields"
                    ),
                ),
                (
                    "formats",
                    models.JSONField(
                        default=dict,
                        help_text="Date and number format specifications per column",
                    ),
                ),
                (
                    "defaults",
                    models.JSONField(
                        default=dict,
                        help_text="Default values for missing optional columns",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_mappings",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "column_mappings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["company", "status"], name="uploads_company_751fdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["created_at"], name="uploads_created_b3d1d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(fields=["status"], name="uploads_status_832574_idx"),
        ),
        migrations.AddIndex(
            model_name="rawtransaction",
            index=models.Index(
                fields=["company", "transaction_date"],
                name="raw_transac_company_e0b298_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawtransaction",
            index=models.Index(
                fields=["company", "product_id"], name="raw_transac_company_5de8b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawtransaction",
            index=models.Index(
                fields=["company", "customer_id"], name="raw_transac_company_843d95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawtransaction",
            index=models.Index(
                fields=["company", "category"], name="raw_transac_company_b66ce7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawtransaction",
            index=models.Index(
                fields=["transaction_date"], name="raw_transac_transac_ef87a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawtransaction",
            index=models.Index(
                fields=["upload"], name="raw_transac_upload__e39305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataupdate",
            index=models.Index(
                fields=["company", "period_type"], name="data_update_company_9afa7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataupdate",
            index=models.Index(
                fields=["timestamp"], name="data_update_timesta_4ac1ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataupdate",
            index=models.Index(
                fields=["upload"], name="data_update_upload__90509e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columnmapping",
            index=models.Index(
                fields=["company", "is_default"], name="column_mapp_company_157da9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columnmapping",
            index=models.Index(
                fields=["created_at"], name="column_mapp_created_5aae92_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="columnmapping",
            unique_together={("company", "mapping_name")},
        ),
    ]
